### ISSUE TITLE
Activities tab pans horizontally too. But it should be disabled.

### ISSUE THREAD

**Issue by jup014** [kpwhri/heartsteps#219]
Environment: ios 14, iphone 8

**Comment by nickdotreid** [comment]
I think I just fixed this issue by getting rid of those gray boxes.

@jup014 Can you check this error is fixed, and if so close this ticket?

**Comment by jup014** [comment]
well … still happening

https://youtube.com/shorts/Mm-4v2ZZn3E?feature=share

Sent from my iPhone

On Jul 14, 2021, at 7:33 PM, Nick Reid ***@***.***> wrote:

﻿

I think I just fixed this issue by getting rid of those gray boxes.

@jup014<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jup014&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=kKGslmPJhBdJjSKuBtQgKw&m=Wxnw6bWQq_8_dGAiXdEzwAVRtZ7ElOqeKvCc_DhfCWQ&s=N-naysGDMyGIVHZrHPZt5MqpyF6NC9wqrUarLhZ0mn0&e=> Can you check this error is fixed, and if so close this ticket?
